<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-06IB4115" ignored="1" name="Default test(failed)" tests="1" failures="1" timestamp="2021-06-18T18:41:31 IST" time="0.061" errors="0">
  <testcase name="verifyName" time="0.009" classname="Methods.Repeat1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Methods.Repeat1.verifyName(Repeat1.java:58)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyName -->
  <testcase name="verifyName1" time="0.0" classname="Methods.Repeat1">
    <ignored/>
  </testcase> <!-- verifyName1 -->
</testsuite> <!-- Default test(failed) -->
